# -*- coding: utf-8 -*-
"""jiot_hotstar_dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LIbIB_O46jtdX1m73_FxB7OM7Esmaii
"""

# jiot_hotstar_dashboard.py
# JioHotstar Interactive Dashboard (Dash + Plotly)
# Run: python jiot_hotstar_dashboard.py
# Make sure Users.csv, Content.csv, Viewing.csv are in the same folder.

import pandas as pd
import numpy as np
from datetime import datetime

import dash
from dash import dcc, html, dash_table, Input, Output, State
import plotly.express as px
import plotly.graph_objects as go

# ----------------------------
# 1) Load data
# ----------------------------
users = pd.read_csv("Users.csv", parse_dates=["JoinDate"], dayfirst=True)
content = pd.read_csv("Content.csv")
viewing = pd.read_csv("Viewing.csv", parse_dates=["WatchDate"], dayfirst=True)

# This ensures 'UserID' columns have the same data type (string) for merging.
users['UserID'] = users['UserID'].astype(str)
viewing['UserID'] = viewing['UserID'].astype(str)

# Merge into master dataframe
df = viewing.merge(users, on="UserID", how="left").merge(content, on="ContentID", how="left")

# Ensure types
df['WatchDuration(hrs)'] = pd.to_numeric(df['WatchDuration(hrs)'], errors='coerce').fillna(0)
df['RatingGiven'] = pd.to_numeric(df['RatingGiven'], errors='coerce').fillna(np.nan)
df['IMDbRating'] = pd.to_numeric(df['IMDbRating'], errors='coerce').fillna(np.nan)

# Minimal preprocessing: add month/year column for timeseries
df['WatchMonth'] = df['WatchDate'].dt.to_period('M').dt.to_timestamp()

# ----------------------------
# 2) Helper functions
# ----------------------------
def filtered_df(lang, genre, plan, state, start_date, end_date):
    d = df.copy()
    if lang and 'All' not in lang:
        d = d[d['Language'].isin(lang)]
    if genre and 'All' not in genre:
        d = d[d['Genre'].isin(genre)]
    if plan and 'All' not in plan:
        d = d[d['SubscriptionPlan'].isin(plan)]
    if state and 'All' not in state:
        d = d[d['State'].isin(state)]
    if start_date:
        d = d[d['WatchDate'] >= pd.to_datetime(start_date)]
    if end_date:
        d = d[d['WatchDate'] <= pd.to_datetime(end_date)]
    return d

def kpis(df_filtered):
    total_views = len(df_filtered)
    avg_watch = round(df_filtered['WatchDuration(hrs)'].mean() if total_views>0 else 0, 2)
    avg_rating = round(df_filtered['RatingGiven'].mean() if df_filtered['RatingGiven'].notnull().any() else 0, 2)
    unique_users = df_filtered['UserID'].nunique()
    return total_views, avg_watch, avg_rating, unique_users

# ----------------------------
# 3) Dash app layout
# ----------------------------
app = dash.Dash(__name__)
app.title = "JioHotstar Analytics Dashboard"

# Options for filters
language_options = ['All'] + sorted(df['Language'].dropna().unique().tolist())
genre_options = ['All'] + sorted(df['Genre'].dropna().unique().tolist())
plan_options = ['All'] + sorted(df['SubscriptionPlan'].dropna().unique().tolist())
state_options = ['All'] + sorted(df['State'].dropna().unique().tolist())

app.layout = html.Div(style={'font-family':'Arial, sans-serif', 'margin': '12px'}, children=[
    html.H2("JioHotstar — Interactive Data Analysis Dashboard", style={'textAlign':'center'}),
    html.Div([
        html.Div([
            html.Label("Language"),
            dcc.Dropdown(id='lang-filter', options=[{'label':x,'value':x} for x in language_options],
                         value=['All'], multi=True, placeholder="Select languages")
        ], style={'width':'20%', 'display':'inline-block', 'verticalAlign':'top', 'paddingRight':'10px'}),

        html.Div([
            html.Label("Genre"),
            dcc.Dropdown(id='genre-filter', options=[{'label':x,'value':x} for x in genre_options],
                         value=['All'], multi=True, placeholder="Select genres")
        ], style={'width':'20%', 'display':'inline-block', 'verticalAlign':'top','paddingRight':'10px'}),

        html.Div([
            html.Label("Subscription Plan"),
            dcc.Dropdown(id='plan-filter', options=[{'label':x,'value':x} for x in plan_options],
                         value=['All'], multi=True)
        ], style={'width':'20%', 'display':'inline-block', 'verticalAlign':'top','paddingRight':'10px'}),

        html.Div([
            html.Label("State"),
            dcc.Dropdown(id='state-filter', options=[{'label':x,'value':x} for x in state_options],
                         value=['All'], multi=True)
        ], style={'width':'20%', 'display':'inline-block', 'verticalAlign':'top'}),
    ], style={'marginBottom':'15px'}),

    html.Div([
        html.Div([
            html.Label("Start Date"),
            dcc.DatePickerSingle(id='start-date', date=df['WatchDate'].min().date())
        ], style={'display':'inline-block', 'marginRight':'20px'}),
        html.Div([
            html.Label("End Date"),
            dcc.DatePickerSingle(id='end-date', date=df['WatchDate'].max().date())
        ], style={'display':'inline-block'})
    ], style={'marginBottom':'20px'}),

    # KPI cards
    html.Div(id='kpi-row', style={'display':'flex', 'justifyContent':'space-between', 'marginBottom':'20px'}),

    # Row: Timeseries + Top genres
    html.Div([
        html.Div(dcc.Graph(id='timeseries-views'), style={'width':'65%', 'display':'inline-block'}),
        html.Div(dcc.Graph(id='top-genres'), style={'width':'33%', 'display':'inline-block', 'verticalAlign':'top'}),
    ], style={'marginBottom':'20px'}),

    # Row: subscription pie + top states + heatmap
    html.Div([
        html.Div(dcc.Graph(id='subs-pie'), style={'width':'32%', 'display':'inline-block'}),
        html.Div(dcc.Graph(id='top-states'), style={'width':'33%', 'display':'inline-block'}),
        html.Div(dcc.Graph(id='genre-lang-sunburst'), style={'width':'33%', 'display':'inline-block'}),
    ], style={'marginBottom':'20px'}),

    # Top titles table
    html.H4("Top Titles (by view count)"),
    dash_table.DataTable(
        id='top-titles-table',
        columns=[
            {'name':'Title','id':'Title'},
            {'name':'Type','id':'Type'},
            {'name':'Language','id':'Language'},
            {'name':'Genre','id':'Genre'},
            {'name':'Views','id':'Views'},
            {'name':'Avg Rating','id':'AvgRating'},
            {'name':'Avg Watch Hrs','id':'AvgWatch'}
        ],
        page_size=10,
        style_table={'overflowX':'auto'},
        style_cell={'textAlign':'left', 'padding':'6px'},
    ),

    html.Div(style={'height':'30px'}),
    html.Div("Tip: Use filters above to slice the data. Refresh the browser if the app becomes unresponsive.", style={'color':'gray', 'fontSize':'12px'})
])

# ----------------------------
# 4) Callbacks
# ----------------------------
@app.callback(
    [
        Output('kpi-row', 'children'),
        Output('timeseries-views', 'figure'),
        Output('top-genres', 'figure'),
        Output('subs-pie', 'figure'),
        Output('top-states', 'figure'),
        Output('genre-lang-sunburst', 'figure'),
        Output('top-titles-table', 'data')
    ],
    [
        Input('lang-filter', 'value'),
        Input('genre-filter', 'value'),
        Input('plan-filter', 'value'),
        Input('state-filter', 'value'),
        Input('start-date', 'date'),
        Input('end-date', 'date'),
    ]
)
def update_dashboard(lang, genre, plan, state, start_date, end_date):
    # Normalize input types
    # If users select ['All'] treat as no filter
    lang_sel = [] if (not lang or 'All' in lang) else lang
    genre_sel = [] if (not genre or 'All' in genre) else genre
    plan_sel = [] if (not plan or 'All' in plan) else plan
    state_sel = [] if (not state or 'All' in state) else state

    ff = filtered_df(lang_sel, genre_sel, plan_sel, state_sel, start_date, end_date)

    # KPI cards
    total_views, avg_watch, avg_rating, unique_users = kpis(ff)
    kpi_children = [
        html.Div([
            html.H6("Total Views"),
            html.H3(f"{total_views}", style={'color':'#2A9D8F'})
        ], style={'padding':'12px', 'border':'1px solid #e6e6e6', 'borderRadius':'6px', 'width':'24%','textAlign':'center'}),
        html.Div([
            html.H6("Avg Watch (hrs)"),
            html.H3(f"{avg_watch}", style={'color':'#E76F51'})
        ], style={'padding':'12px', 'border':'1px solid #e6e6e6', 'borderRadius':'6px', 'width':'24%','textAlign':'center'}),
        html.Div([
            html.H6("Avg Rating"),
            html.H3(f"{avg_rating}", style={'color':'#457B9D'})
        ], style={'padding':'12px', 'border':'1px solid #e6e6e6', 'borderRadius':'6px', 'width':'24%','textAlign':'center'}),
        html.Div([
            html.H6("Unique Users"),
            html.H3(f"{unique_users}", style={'color':'#264653'})
        ], style={'padding':'12px', 'border':'1px solid #e6e6e6', 'borderRadius':'6px', 'width':'24%','textAlign':'center'})
    ]

    # Time series: views per month
    ts = ff.groupby('WatchMonth').size().reset_index(name='Views')
    if ts.empty:
        ts = pd.DataFrame({'WatchMonth':[pd.to_datetime(start_date) if start_date else df['WatchMonth'].min()], 'Views':[0]})
    fig_ts = px.line(ts, x='WatchMonth', y='Views', markers=True, title="Views Over Time (by Month)")
    fig_ts.update_layout(margin=dict(l=10,r=10,t=40,b=10))

    # Top genres
    topg = ff['Genre'].value_counts().reset_index().rename(columns={'index':'Genre', 'Genre':'Views'})
    if topg.empty:
        topg = pd.DataFrame({'Genre':['No Data'], 'Views':[0]})
    fig_genre = px.bar(topg.head(10), x='Genre', y='Views', title="Top Genres", text='Views')
    fig_genre.update_layout(margin=dict(l=10,r=10,t=40,b=10))

    # Subscription pie
    subs = ff['SubscriptionPlan'].value_counts().reset_index().rename(columns={'index':'Plan', 'SubscriptionPlan':'Count'})
    if subs.empty:
        subs = pd.DataFrame({'Plan':['No Data'],'Count':[1]})
    fig_subs = px.pie(subs, names='Plan', values='Count', title="Subscription Mix", hole=0.35)
    fig_subs.update_layout(margin=dict(l=10,r=10,t=40,b=10))

    # Top states
    top_states = ff['State'].value_counts().reset_index().rename(columns={'index':'State','State':'Views'})
    if top_states.empty:
        top_states = pd.DataFrame({'State':['No Data'], 'Views':[0]})
    fig_states = px.bar(top_states.head(10), x='State', y='Views', title="Top States by Views", text='Views')
    fig_states.update_layout(margin=dict(l=10,r=10,t=40,b=10))

    # Sunburst: Genre -> Language -> Type
    sun_data = ff.groupby(['Genre','Language','Type']).size().reset_index(name='count')
    if sun_data.empty:
        sun_data = pd.DataFrame({'Genre':['None'], 'Language':['None'], 'Type':['None'], 'count':[1]})
    fig_sun = px.sunburst(sun_data, path=['Genre','Language','Type'], values='count', title="Genre → Language → Type")
    fig_sun.update_layout(margin=dict(l=0,r=0,t=40,b=0))

    # Top titles table
    titles = ff.groupby(['Title','Type','Language','Genre']).agg(
        Views=('ViewID','count'),
        AvgRating=('RatingGiven','mean'),
        AvgWatch=('WatchDuration(hrs)','mean')
    ).reset_index().sort_values('Views', ascending=False)
    titles['AvgRating'] = titles['AvgRating'].round(2)
    titles['AvgWatch'] = titles['AvgWatch'].round(2)
    table_data = titles.head(50).to_dict('records')

    return kpi_children, fig_ts, fig_genre, fig_subs, fig_states, fig_sun, table_data

# ----------------------------
# 5) Run app
# ----------------------------
if __name__ == "__main__":
    app.run(port=8050)